apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    group: school-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image:  deepugeorgejacob/api-gateway:0.1
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server-service.default:8761/eureka/
