apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    group: school-management
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer