apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
  labels:
    group: school-management
spec:
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      port: 7000
  type: ClusterIP