apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image:  deepugeorgejacob/scheduler:0.1
          env:
            - name: EUREKA_SERVER
              value: http://eureka-server-service.default:8761/eureka/