apiVersion: v1
kind: Service
metadata:
  name: school-library-service
  labels:
    group: school-management
spec:
  selector:
    app: school-library
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP